### ISSUE TITLE
项目启动不了，详细报错信息如下：

### ISSUE THREAD

**Issue by WuHuaJi0** [shinygang/Vue-cnodejs#33]
克隆好了项目，npm install 安装第三方模块
node server.js 准备启动项目，报错信息如下：

```
➜  Vue-cnodejs git:(master) ✗ node server.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'memory-fs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/wuhuaji/sync/code/Vue-cnodejs/node_modules/.npminstall/webpack-dev-middleware/1.6.1/webpack-dev-middleware/middleware.js:5:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

```

根据报错信息，似乎与webpack-dev-middleware相关，于是安装这个模块，但是没用，请问这是什么回事呢？

另还有个问题，npm run dist 也报错，报错信息如下：

```
➜  Vue-cnodejs git:(master) ✗ npm run dist

> Vue-Cnodejs@1.0.0 dist /Users/wuhuaji/sync/code/Vue-cnodejs
> NODE_ENV=development gulp

module.js:327
    throw err;
    ^

Error: Cannot find module 'globby'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/wuhuaji/sync/code/Vue-cnodejs/node_modules/.npminstall/del/2.2.0/del/index.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dist"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! Vue-Cnodejs@1.0.0 dist: `NODE_ENV=development gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Vue-Cnodejs@1.0.0 dist script 'NODE_ENV=development gulp'.
npm ERR! This is most likely a problem with the Vue-Cnodejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Vue-Cnodejs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls Vue-Cnodejs
npm ERR! There is likely additional logging output above.
```

不知这是什么原因所致？

本人node只是了解，还请多多指教

**Comment by shinygang** [comment]
@WuHuaJi0 你好，请问你是什么环境？

**Comment by WuHuaJi0** [comment]
我的环境是：
mac osx ，
node -version：4.4
不知还需要提供其他信息吗？

**Comment by shinygang** [comment]
我和你的环境一样啊，我刚才试验了，正常啊，是不是你模块没安装对

**Comment by WuHuaJi0** [comment]
你刚才的试验，是重写克隆，并安装所有的依赖吗？

我的顺序是这样的：克隆项目->安装依赖->启动服务。
但是在安装依赖的时候，有几个提示：

```
cssnext-loader 
graceful-fs 
lodash
```

等这几个第三方模块，或已经改名，或已经不推荐使用，或版本号低了，不知道是不是这里的问题？能不能检查一下package.json中的依赖是否有需要更新的情况？

**Comment by shinygang** [comment]
对，今晚重新clone的，我刚才提交了下代码，把不要的依赖删除了。你重新试一试，不行加我qq 429517385.

**Comment by WuHuaJi0** [comment]
好的，我试下，多谢哈 ：）

**Comment by WuHuaJi0** [comment]
这里的问题是，没能安装所有的npm包。
为什么会这样呢？gfw在作恶了，代理之后，重新安装第三方包。
另外，有一点需要注意，不能使用cnpm 来替代 npm 安装，还是上代理吧 。

**Comment by perfectyang** [comment]
写的很6啊，我跑跑看
