### ISSUE TITLE
node server.js 的时候报错。请告诉我下是啥原理 😢

### ISSUE THREAD

**Issue by gggso** [shinygang/Vue-cnodejs#35]
module.js:341
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/wwwroot/Vue-cnodejs/node_modules/readable-stream/lib/_stream_readable.js:6:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

**Comment by shinygang** [comment]
你这个报错很可能是模块没安装好，你重新安装下模块。
