### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by RifeWang** [shinygang/Vue-cnodejs#81]
windows环境下npm install安装依赖包报错：
```
npm WARN prefer global node-gyp@3.5.0 should be installed with -g

> node-sass@3.13.1 install F:\vue-cnodejs\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-48_binding.node":

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall F:\vue-cnodejs\node_modules\node-sass
> node scripts/build.js

Binary found at F:\vue-cnodejs\node_modules\node-sass\vendor\win32-x64-48\binding.node
Testing binary
Binary has a problem: Error: %1 is not a valid Win32 application.
\\?\F:\vue-cnodejs\node_modules\node-sass\vendor\win32-x64-48\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (F:\vue-cnodejs\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (F:\vue-cnodejs\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
Building the binary locally
Building: C:\Program Files\nodejs\node.exe F:\vue-cnodejs\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'F:\\vue-cnodejs\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.5.0
gyp info using node@6.9.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\vue-cnodejs\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\vue-cnodejs\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\vue-cnodejs\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\vue-cnodejs\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\vue-cnodejs\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at F:\vue-cnodejs\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\vue-cnodejs\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\vue-cnodejs\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\vue-cnodejs\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\vue-cnodejs\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\vue-cnodejs\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at F:\vue-cnodejs\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (F:\vue-cnodejs\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\vue-cnodejs\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\vue-cnodejs\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\vue-cnodejs\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\vue-cnodejs\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at F:\vue-cnodejs\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (F:\vue-cnodejs\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\vue-cnodejs\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\vue-cnodejs\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\vue-cnodejs\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\vue-cnodejs\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at F:\vue-cnodejs\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (F:\vue-cnodejs\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at Object.<anonymous> (F:\vue-cnodejs\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at F:\vue-cnodejs\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\vue-cnodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd F:\vue-cnodejs\node_modules\node-sass
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\vue-cnodejs\npm-debug.log

```

**Comment by shinygang** [comment]
@RifeWang node-sass安装问题，模块安装问题，请自行google哈。
